CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(100) NOT NULL,
  "password" varchar(50) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(30) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(80) NOT NULL,
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL,
  "categorie_id" int NOT NULL
);

CREATE TABLE "videos_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar(80) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "user_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categorie_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "videos_course" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO users (name, email, password, age, role_id)
VALUES 
    ('Daniel', 'daniel@gmail.com', '1234', 34, 1),
    ('Alejandra', 'alejandra@gmail.com', '1234', 25, 2),
    ('Esteban', 'esteban@gmail.com', '1234', 32, 2),
    ('Alberto', 'alberto@gmail.com', '1234', 33, 3);

INSERT INTO levels (level) VALUES ('beginner'), ('intermediate'), ('advanced');

INSERT INTO categories (name) VALUES ('front-end'), ('back-end');

INSERT INTO courses (title, description, level_id, teacher_id, categorie_id)
VALUES
  ('html', 'lenguaje de marcado para la elaboración de páginas web.', 1, 2, 1),
  ('postgresql', 'es un sistema de gestión de bases de datos relacional orientado a objetos', 2, 3, 2);

INSERT INTO videos_course (title, url, course_id)
VALUES
  ('structure', 'https:/www.structor....', 1),
  ('databases', 'https:/www.databases....', 2);
